### ISSUE TITLE
Hentaienvy not working

### ISSUE THREAD

**Issue by cc713** [gan-of-culture/get-sauce#101]
CDNPrefixSrcURLPart of hentaienvy.com has been changed to "js/main_v4.js".
CDNPrefixSrcURLPart of imhentai.xxx and hentairox.com have also been changed to "js/main_94xa9x.js" and "js/main_v8.js", but seems working fine.

**Comment by gan-of-culture** [comment]
Wow I have never seen them change the main file, but I will now parse the correct main.js file from their hompage. Thanks for your work! 👍
