### ISSUE TITLE
Add rokuhentai and orzqwq, bug report

### ISSUE THREAD

**Issue by cc713** [gan-of-culture/get-sauce#103]
Feature requests:
1. rokuhentai: <https://rokuhentai.com>
2. orzqwq: <https://orzqwq.com>
---
Bugs:
1. Get "URL parse failed" when trying to download from hentai2read.com.
2. Get "dial tcp: lookup cdn.pururin.io: no such host" when trying to download from pururin.to.
3. Get "fatal error: concurrent map writes" or "fatal error: concurrent map iteration and map write" frequently when using htdoujin extractors with many download workers, e.g:100. Previous version does not have this issue.

**Comment by gan-of-culture** [comment]
regarding the bugs:
1. Works for me. Can you send me the URL of what you are trying to download?
2. Will be fixed with the next release
3. Will also be fixed with the next release

**Comment by cc713** [comment]
Seems to be caused by Cloudflare protection. Works after using proxy.

**Comment by gan-of-culture** [comment]
I added orzqwq: https://orzqwq.com/ but [rokuhentai.com](https://rokuhentai.com/) doesn't work for me. If I click on any of the galleries one image appears and nothing happens. Can't navigate etc. so I won't add it for now.
