### ISSUE TITLE
orzqwq incorrect url parsing and details about rokuhentai

### ISSUE THREAD

**Issue by cc713** [gan-of-culture/get-sauce#104]
Get 9 urls of gif when using `get-sauce -j https://orzqwq.com/manga/badatgarbage-lilina-x-gonzalez-fire-emblem-the-binding-blade/`, but the gallery actually has only one gif.

---
The default view of rokuhentai is from right to left.
To change the view, click menu button in the top left corner of the gallery.
Url of images in rokuhentai gallery takes simple format of
`https://rokuhentai.com/_images/pages/<galleryID>/<page>.jpg`, `<page>` index start from 0.
For example, "https://rokuhentai.com/_images/pages/voy6xm/0.jpg" is the first image of the gallery "https://rokuhentai.com/voy6xm".

**Comment by gan-of-culture** [comment]
Hi!

I see the galleries do have different file types, so I made an adjustment to account for that and it will be included in the next release. Regarding rokuhentai.com: I really have no motivation to make/maintain a extractor for such a bad website. (imo) If you or anyone else makes a PR I'll consider adding it.

p.s. if I change the reading direction to top -> bottom it also works for me

**Comment by gan-of-culture** [comment]
also if you find any other bugs please let me know. I personally actively only use a few websites so I might be missing some bugs as you already noticed 👍
