### ISSUE TITLE
[BUG] Don't download by site hitomi.la

### ISSUE THREAD

**Issue by sixtynicooo** [gan-of-culture/get-sauce#114]
Good morning, first of all I would like to congratulate you because this program is very useful. Now I'm trying to use it to download some manga in Italian, but I'm having difficulty with the following codes 'go run https://hitomi.la/reader/2464336.html#1-'. I think what I've written is correct, maybe the website has been updated and the software hasn't?

terminal
```
go run https://hitomi.la/reader/2464336.html#1-

error 
2023/02/15 17:06:51 URL parse failed
exit status 1
```
I hope I was clear
Good day

**Comment by gan-of-culture** [comment]
Hi, thanks for reporting your issue. Please try it again with the URL of the gallery which in your example would be:
`https://hitomi.la/manga/puppet-club-%7C-club-di-yoga-italiano-2464336.html#1`

To download a specific page you can check out the parameter `-p`.

**Comment by sixtynicooo** [comment]
Good morning,
thanks for the availability but I still have problems. First of all when you have to use get-sauce.exe you mean that you have to save the file located at the site https://github.com/gan-of-culture/get-sauce/releases and in my case I have windows and the file inside I put it in the get-sauce-master folder together with the other files? Or do you have to run the file? This last action apparently does not leave me. Meanwhile I tried with all 3 files get-sauce.exe one at a time and together with the other files and I ran from terminal
``
get-sauce.exe "https://hitomi.la/manga/puppet-club-%7C-italian-yoga-club-2464336.html#1"
``
but i got as error
``
no limit values found at: https://ltn.hitomi.la/gg.js .
``
I hope I was clear, I await a kind reply

**Comment by gan-of-culture** [comment]
Hi, there are two ways to run get-sauce:
1. Using the executable for your OS which can be downloaded from the "releases" page of this repo
2. Using the source code and executing it using Golang `go run main.go ...`

Please refer to the Readme.md file for further instructions.

Using the newest version I was able to download `https://hitomi.la/manga/puppet-club-%7C-italian-yoga-club-2464336.html#1` with no problem.
![img](https://media.discordapp.net/attachments/554672804578983957/1075937892494487742/image.png)

**Comment by watchhentai** [comment]
Hello @gan-of-culture please add my hentai website to the list **[Watch Hentai](https://watchhentai.net)**

We average 50k daily users and this tool can help them.

**Comment by sixtynicooo** [comment]
Hello, still not going, I attach 2 screenshots to show that with the same code on https://hitomi.la/manga/inmushi-no-ikenie-italiano-1059339.html#1 it doesn't work for me while on https:/ /orzqwq.com/manga/q-hatsu-date-wa-lingerie-shop-shop-lingerie-otokonoko-wa-itsudemo-moteki-2-english/ Download me, later try on another computer, I'm sure I have downloaded both go and FFmpeg otherwise it wouldn't download anything, then I also managed to get get-sauce.exe to work.

hitomi.la
Not download
![Screenshot (102)](https://user-images.githubusercontent.com/43573782/219613574-174ceca5-4a6e-4afa-a7dc-2e6537fe36bc.jpg)

[orzqwq](https://orzqwq.com/
Download
![image (1)](https://user-images.githubusercontent.com/43573782/219615149-3cc57468-37bd-4c32-ba21-5dfea707e568.jpg)

**Comment by sixtynicooo** [comment]
Request
could it be an ip problem? or something like that? Because I tried with the Windscribe vpn and it works but it doesn't work without it, are there other solutions? I could use the tor network I was able to get it working.

**Comment by sixtynicooo** [comment]
Since the problem is perhaps a block or something like that because in 2 other sites (at least) the hentai manga are downloaded while on hitomi.la I didn't think of adding the header, do you have any advice? I put the user-agent, for cookies what could I put? I would like to make a few attempts so maybe if it resolves it maybe it could be useful in the future
Good day

**Comment by gan-of-culture** [comment]
get-sauce should use the default proxy that is configured in the windows settings, but there is no TOR support. Can you save the output of `https://ltn.hitomi.la/gg.js` as a file and attach it?

**Comment by sixtynicooo** [comment]
[gg.zip](https://github.com/gan-of-culture/get-sauce/files/10773936/gg.zip)

Hello, I attach the js file and then I tried with another computer and it gives me the same error so it's probably a network problem or I don't know, I hope the js file is zipped (you couldn't update with js on the comment) you can understand something more, good day

**Comment by gan-of-culture** [comment]
hmmm that's weird. The `gg.js` file looks good to me. Sorry I can't help you then since I can't reproduce the error :(

**Comment by sixtynicooo** [comment]
I understand, patience at most I will use a vpn for a month, however there are other sites where I have to download. Thanks for your time and have a good day

**Comment by sixtynicooo** [comment]
Good news , i tried with my mobile hospot with pc and it works !!! With home wifi it doesn't work and I don't know why. Mystery. Thanks for everything
