### ISSUE TITLE
Bug Size image

### ISSUE THREAD

**Issue by sixtynicooo** [gan-of-culture/get-sauce#116]
Hi, I would like to ask something even if I don't know if it can be considered a bug because this problem is also present on the code page where there are instructions. The problem is the following (code taken directly from https://github.com/gan-of-culture/get-sauce)
```
get-sauce -i https://nhentai.net/g/364616/ https://nhentai.net/g/364591/
OUTPUT 
  Site: https://nhentai.net
  Title: Matsuri tte Ii na
  Type: image
  Streams: # All available qualities
      [0] -------------------
      Type: image
      Quality: unknown
      Parts: 31
      Size: 0B  
      # download with: get-sauce -s 0 ...
```
the size is 0 , you could when you write get-sauce -i https://nhentai.net/g/364616/ https://nhentai.net/g/364591/ with -i also the Size i.e. the sum of the sizes of the images. In my opinion it is to be considered a bug, but maybe there are important complications. However, it is a way to make this excellent project more complete.

**Comment by gan-of-culture** [comment]
Hi, calculating the sum of all filesizes would require to request each page one which would slow down get-sauce significantly and spam the website providing the content, that's why I decided against doing this for doujins for example.

**Comment by sixtynicooo** [comment]
Of course, I just wanted to understand why there was this problem, before asking, however, I checked the issues section and I hadn't found an answer
thanks for your answer
