### ISSUE TITLE
hentaihaven.xxx: URL parse failed

### ISSUE THREAD

**Issue by marek22k** [gan-of-culture/get-sauce#123]
**Describe the bug**
Episodes according to the scheme `https://hentaihaven.xxx/watch/[series]/episode-[num]/` can be downloaded without problems, but not OVAs:

**To Reproduce**
```
$get-sauce https://hentaihaven.xxx/watch/fuyu-no-semi/ova-1/
2023/05/14 20:56:52 URL parse failed
```

**Expected behavior**
Downloads normally like a episode.

**Desktop (please complete the following information):**
 - OS: Parrot OS (Debian 11-based)
 - Can the video or image be viewed on the website? Yes

Edit: Same applies for URLs like `https://hentaihaven.xxx/watch/ai-no-kusabi/episode-1-1999/`

**Comment by gan-of-culture** [comment]
Thanks for reporting the issue. Yes indeed this is a bug because the Regex parsing the URLs only allows episode-[num] until now. I will update it.

**Comment by gan-of-culture** [comment]
Please check if it works now.
