### ISSUE TITLE
UncensoredHentai.xxx Video Subtitles

### ISSUE THREAD

**Issue by JonyyLemon** [gan-of-culture/get-sauce#128]
I can't get subtitles to the videos I'm downloading,

I tried downloading a video through uncensored hentai but whatever command I use the video does not contain the subtitles, I tried using '-k', and '-c' but all ended up with a video that does not contain subtitles.

**Comment by gan-of-culture** [comment]
Hi, please provide the URL to the video which you are trying to download.

**Comment by gan-of-culture** [comment]
I published a new version. Please check if it works now. Thanks!

**Comment by JonyyLemon** [comment]
Sorry for not replying to the earlier message, haven't got the time to check up on the site. Thanks for fixing the bug as well- surely will check it out.
