### ISSUE TITLE
[Bug] `strconv.Atoi: parsing "": invalid syntax:`

### ISSUE THREAD

**Issue by erickyun** [gan-of-culture/get-sauce#140]
**Describe the bug**
Hi,

I can't download from specific URL `https://oppai.stream/watch?e=Imouto-wa-GAL-Kawaii-1` when I execute 
```
get-sauce -i https://oppai.stream/watch?e=Imouto-wa-GAL-Kawaii-1
2023/12/16 17:11:44 strconv.Atoi: parsing "": invalid syntax: Imouto-wa-GAL-Kawaii-1
```

I had not problem with other urls from this site but this URL did give strconv.Atoi error?

**Comment by gan-of-culture** [comment]
Seems like you got unlucky with that video since it contained a "null" key for available resolutions. I will fix get-sauce that it will not try to parse those.

**Comment by erickyun** [comment]
> Seems like you got unlucky with that video since it contained a "null" key for available resolutions. I will fix get-sauce that it will not try to parse those.

Thank you it works fine now.
