### ISSUE TITLE
External Subtitle File Download

### ISSUE THREAD

**Issue by iamvortex123** [gan-of-culture/get-sauce#143]
Not reporting any bug just wanted to know is there any way to get the subtitle file as well or do we need to extract it from the merged mp4 file ourselves? tried `-c 0` option but it downloads the subtitles and merges it to the video and audio file. Was wondering if there was a way for the program to leave a copy of the subtitle file also

**Comment by gan-of-culture** [comment]
Hi,

there is the option
`-k             Keep video, audio and subtitles. Don't merge using ffmpeg`
If you use it the subtitle should be kept a separate file and not be merged. Please try it and let me know if it worked for you.

**Comment by iamvortex123** [comment]
> Hi,
> 
> there is the option `-k Keep video, audio and subtitles. Don't merge using ffmpeg` If you use it the subtitle should be kept a separate file and not be merged. Please try it and let me know if it worked for you.

yep it works, thanks a lot
