### ISSUE TITLE
GET-SAUCE Command isn't working.

### ISSUE THREAD

**Issue by BoiledEggPie** [gan-of-culture/get-sauce#145]
I installed get-sauce through go install github.com/gan-of-culture/get-sauce@latest, and redirected ffmpeg to path, yet keeps giving me a remote error, saying tls: access denied. I've used this command on another device and it worked fine then.

![image](https://github.com/gan-of-culture/get-sauce/assets/129612640/f84ca7e4-e8a5-4a05-88a5-ff729dd736e0)

Device name	DESKTOP-QNRBH3V
Processor	Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	2FF46E28-B941-4F69-AEE7-FBCC876C362B
Product ID	00330-53435-22499-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by gan-of-culture** [comment]
Hi,

thanks for opening an issue. Unfortunately it works just fine on my system (Win 11 x64). Can you please try it again and check if it works now?

**Comment by BoiledEggPie** [comment]
I checked again as you've suggested - I reinstalled it, and seems like it works fine. Sorry for the false report and thank you for you time.

**Comment by BoiledEggPie** [comment]
Though does yours do the installation process like this- 
![image](https://github.com/gan-of-culture/get-sauce/assets/129612640/3166c342-f950-4f99-bd0d-485f74c6a6ad)

**Comment by gan-of-culture** [comment]
Yes. That is how the downloading looks like. The progress bar is provided by another package. You can find it in this project's go.mod file.
