### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by Conehead123** [gan-of-culture/get-sauce#148]
I cant seem to get it working, and I keep getting "index out of range [-1]". Im using the latest build and have tried other websites, and I either get that or something similar. I noticed some other people posting about similar issues with index out of range, but none of them seem to work for me. Please help :(

![Screenshot 2024-08-10 024128](https://github.com/user-attachments/assets/12faadd7-80f4-4d31-8208-b19ec188605e)

**Comment by gan-of-culture** [comment]
Hi,

it works for me. Can you please do me a favor and wrap the URL in `""`?

This is the output you should get:
```
get-sauce -i "https://hstream.moe/hentai/futei-with-the-animation-1"

 Site:      https://hstream.moe/
 Title:     Futei with... The Animation - 1
 Type:      video
 Captions:  # All available languages

     [0]  -------------------
     Language:            English
     # download with: get-sauce -c 0 ...


 Streams:   # All available qualities
     [0]  -------------------
     Type:            video
     Info:            av01.0.12M.08
     Quality:         2880x1920
     Parts:           169
     Size:            0 B
     # download with: get-sauce -s 0 ...


     [1]  -------------------
     Type:            audio
     Info:            mp4a.40.2
     Quality:         x
     Parts:           169
     Size:            0 B
     # download with: get-sauce -s 1 ...


     [2]  -------------------
     Type:            video
     Info:            av01.0.08M.08
     Quality:         1920x1080
     Parts:           169
     Size:            0 B
     # download with: get-sauce -s 2 ...


     [3]  -------------------
     Type:            video
     Info:            avc1.64001f
     Quality:         1280x720
     Parts:           169
     Size:            0 B
     # download with: get-sauce -s 3 ...
```

**Comment by Conehead123** [comment]
Wrapping the quotations in "" still gave me the same result, but I tried something different that seemed to work for me. Switching to a different Wifi network seemed to get it to work properly for me though, and switching back  to the original network afterwards seemed to fix it permanently. Thanks for the help :)
