### ISSUE TITLE
Cant get captions for videos

### ISSUE THREAD

**Issue by Conehead123** [gan-of-culture/get-sauce#150]
Im downloading videos from hstream.moe where the captions aren't directly embedded and using the `-c 0` and `-k 0` args, but cannot seem to see the captions or get them as an  individual file. In the case of  `-k 0`, I only get the ACC and MP4 files, and cant seem to find the caption file anywhere.  Any help? 
![Screenshot 2024-08-12 194825](https://github.com/user-attachments/assets/1b573fcd-eb15-4e9c-b236-1b30a709cf7c)
![Screenshot 2024-08-12 195302](https://github.com/user-attachments/assets/238c16f2-289e-4578-b455-8026434bc44a)

**Comment by gan-of-culture** [comment]
Hi,

if you run it with both arguments you should get your desired result.
`get-sauce -c 0 -k "https://hstream.moe/hentai/shikijou-kyoudan-1"`
```
.rw-r--r--  16M anon 13 Aug 23:17 'Shikijou Kyoudan - 1.aac'
.rw-r--r-- 369M anon 13 Aug 23:17 'Shikijou Kyoudan - 1.mp4'
.rw-r--r--  34k anon 13 Aug 23:17 'Shikijou Kyoudan - 1_caption_English.ass'
```
