### ISSUE TITLE
Unknown Webp in Hstream

### ISSUE THREAD

**Issue by Naikkusu** [gan-of-culture/get-sauce#152]
**Describe the bug**
Every time I download in Hstream, instead of the video and subtitles getting downloaded, it downloads the webp of something; it downloads up to 20+ files of webp. 

**Expected behavior**
Endless downloading webp of something i don't even know

**Screenshots**
![image](https://github.com/user-attachments/assets/c4fdd46a-c179-448e-9ffc-1167749ea6b3)
![image](https://github.com/user-attachments/assets/3e16c70c-52b5-4fb7-b390-30d974d26b7e)
![image](https://github.com/user-attachments/assets/b790eaf0-a573-4868-927a-f2e2286cc163)

**Desktop (please complete the following information):**
 - OS: Windows
 - Can the video or image be viewed on the website?

**Additional context**

**Comment by gan-of-culture** [comment]
Hi,

this is normal behaviour the audio and video files are split up into multiple parts on some websites. If you let it run it should download all the parts and then merge them together into the desired file format.
