### ISSUE TITLE
hstream.moe triggers error "requested name valid; no data found"

### ISSUE THREAD

**Issue by Anonym121** [gan-of-culture/get-sauce#153]
I decided to continue downloading the HQ videos from hstream.moe again; but I noticed none work!
Even the ones that I had downloaded back in summer cannot be downloaded now.
Examples:

https://hstream.moe/hentai/aniyome-wa-ijippari-1
https://hstream.moe/hentai/1ldk-jk-ikinari-doukyo-micchaku-hatsu-ecchi-1
https://hstream.moe/hentai/kansen-5-the-daybreak-1

All of them give the same kind of error:
```
get-sauce -k https://hstream.moe/hentai/aniyome-wa-ijippari-1
2024/10/01 20:38:20 Get "https://hstream.moe/hentai/aniyome-wa-ijippari-1": dial tcp: lookup hstream.moe: getaddrinfow: The requested name is valid, but no data of the requested type was found.: https://hstream.moe/hentai/aniyome-wa-ijippari-1
```
This time, I am using the latest version and I have tested this with VPN/no VPN, at least 3 different wifi networks and 2 computers. One of which is new,bought this week.
So I am sure this time it isn't an issue on my part.

**Comment by Anonym121** [comment]
It seems there is something fundamentally wrong with all wifis in my country (or coincidentally, the ones I tried) that is hampering downloads with get-sauce somehow.
I tried downloading from oppai.stream and it is the same issue. I managed to get it working using my phone wifi and Opera useragent. I didn't test any other browser useragent. Apparently, it doesnt work if the wifi is a different one (including VPN tunnel to exotic places) or if I dont use the opera useragent.
The websites and the videos can be played normally, so idk what exactly is happening.

**Comment by gan-of-culture** [comment]
Hi, thanks for the information. It seems to be that some places encounter some sort of geo blocking. Since it works for me I can't really do anything about it. I will close this issue. People will still be able to search this issue and find your solution.
