### ISSUE TITLE
Koharu.to mirror not able to download

### ISSUE THREAD

**Issue by AllHailTheFox** [gan-of-culture/get-sauce#157]
Great work really love this app. But since koharu.to is down I've tried using the mirror links and it says not found. It would be really great if it works for the mirrors. Thanks

get-sauce -i https://niyaniya.moe/g/24693/6967f8ecb6ab

C:\Users\Downloads\hani\Testing\Tools\get-sauce_Windows_x86_64>get-sauce -i https://niyaniya.moe/g/24693/6967f8ecb6ab

 Site:      niyaniya.moe
 Title:     unknown
 Type:      unknown
 Streams:   # All available qualities
     [0]  -------------------
     Type:            unknown
     Quality:         unknown
     Size:            0 B
     # download with: get-sauce -s 0 ...

**Comment by gan-of-culture** [comment]
Thanks for taking the time to create this issue.

As far as I can see it seems the completely rebranded. I updated the program. Feel free to test it using version 1.3.0.
