### ISSUE TITLE
HentaiStream.moe subtitle isn't downloaded

### ISSUE THREAD

**Issue by zajimumaaa** [gan-of-culture/get-sauce#56]
Hi, thanks for this tool. Does HentaiStream.moe support downloading the subtitle? I tried download from there but it just downloading the video. I checked using browser developer mode and found the subtitle URL in the HTML code, so the video I downloaded have substitle file.
![image](https://user-images.githubusercontent.com/96493674/146977021-455a9e3f-9b49-4b88-ab0c-aa69163f5fff.png)
Thanks

**Comment by gan-of-culture** [comment]
Hi, thanks for your feedback. Currently downloading subtitles is not yet supported for hentaistream.moe. I will take a look at it and implement it :) Please have some patience.

**Comment by gan-of-culture** [comment]
#57

**Comment by gan-of-culture** [comment]
Please download the newest version and try it out.

**Comment by zajimumaaa** [comment]
> Please download the newest version and try it out.

Thanks it's works :)
