### ISSUE TITLE
[BUG] <Hentaibar missing quality>

### ISSUE THREAD

**Issue by freddiehdxd** [gan-of-culture/get-sauce#66]
**Describe the bug**
HentaiBar not showing all the quality

**To Reproduce**
get-sauce -i https://hentaibar.com/videos/1196/tsun-m-gyutto-shibatte-shidoushite-the-animation-episode-1-english-subbed/

**Expected behavior**
To display all quality only displaying 3 instead of 4

**Screenshots**
![image](https://user-images.githubusercontent.com/20363835/151281145-8cbb62a1-c2c3-4006-af11-c4b4dc187c25.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]

**Comment by gan-of-culture** [comment]
Thanks for pointing that out! It will be fixed with the next release.
