### ISSUE TITLE
[BUG] <1kb files from HentaiEra>

### ISSUE THREAD

**Issue by hentaifapper420** [gan-of-culture/get-sauce#75]
**Describe the bug**
When downloading galleries from HentaiEra, I always get 1kb sized blank files (I have FFMPEG installed)

**To Reproduce**
1. Used get-sauce on the following gallery: https://hentaiera.com/gallery/610929/

**Expected behavior**
Images and Gifs downloaded

**Screenshots**
Screenshot of the resulting images:
![image](https://user-images.githubusercontent.com/103375443/162627579-3c6ce242-3984-4d4a-b727-52051460e4ff.png)

Screenshot of FFMPEG:
![image](https://user-images.githubusercontent.com/103375443/162627608-c322d7b2-ab13-4c82-8394-852419d6e5d2.png)

Screenshot of GS:
![image](https://user-images.githubusercontent.com/103375443/162627673-21bd63b1-a66d-4227-a6e1-6ad6c27437f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
N/A

**Comment by gan-of-culture** [comment]
Please download the newest version and try it again. Thanks for reporting :+1:
