### ISSUE TITLE
[BUG] Subtitle doesn't show after 2 or 3 minute [hentaistream.moe]

### ISSUE THREAD

**Issue by erickyun** [gan-of-culture/get-sauce#81]
**Describe the bug**
Subtitle doesn't show after the 2nd or 3rd minute of the video?

**To Reproduce**
1. ` get-sauce -s 0 -c 0 https://hentaistream.moe/970/akane-wa-tsumare-somerareru-1/ `
2. video and subtitle are merged successfully but
3. when I try to play with mpv ( vlc, mx or mpc-hc)
4.  subtitle never appears again after 2 or 3 minute
5. tried to extract subtitle with program and saw subtitle is only downloaded until the 2 or 3 minute

**Expected behavior**
The Whole Subtitle file will be downloaded for the video

**Desktop (please complete the following information):**
 - OS: Android 11 Termux, Xiaomi Redmi Note 8 Pro

**Additional context**
I think this is a ffmpeg problem because in hentaistream.moe's .vtt subtitle
I saw that they put spaces between some lines and ffmpeg skips the whole lines when such space appears.

`Example:`

```
00:02:30.000-xx:xx:xx.000
text text

00:02:57.000-xx:xx:xx.000
text text

text text

00:03:40.000-xx:xx:xx.000
text text

00:03:45.000-xx:xx:xx.000
text text
```

So in 00:02:57.000 there is a space between the lines and because of this.
 ffmpeg does skip 00:02:57.000 line and whatever line comes after so the subtitle file will be only downloaded until 00:02:30.000 minute.

### Edit:
merging the video and .vtt subtitle with mkvmerge without converting the subtitle with ffmpeg solves THİS problem! The problem does not occur with mkvmerge.

Could you also add mkvmerge as dependencies? and change the command for merging(for hentaistream.moe ONLY ofcourse) to use mkvmerge instead of ffmpeg?

**Comment by gan-of-culture** [comment]
there is sanitizing logic for exactly this issue maybe it's different from the cases I had before I'll take a look at it 👍

**Comment by gan-of-culture** [comment]
Looks like it's breaking at here:
```
02:33.210 --> 02:40.630
The Madder
is Plucked
and Dyed

Akane wa Tsumare Somerareru

02:33.210 --> 02:40.630
The Madder
is Plucked
and Dyed

Akane wa Tsumare Somerareru

02:33.210 --> 02:40.630
The Madder
is Plucked
and Dyed

Akane wa Tsumare Somerareru
```
The sanitizing logic currently only removes additional blank lines. I'll make sure to fix it later today. Thanks for reporting the issue!

**Comment by erickyun** [comment]
> The sanitizing logic currently only removes additional blank lines. I'll make sure to fix it later today. Thanks for reporting the issue!

No problem.👍
And Thank you for your answer.

**Comment by gan-of-culture** [comment]
Please try again and if you still have issues don't hesitate another issue! Thanks again for your input :+1:

**Comment by erickyun** [comment]
> Please try again and if you still have issues don't hesitate another issue! Thanks again for your input 👍

İt is working fine now thanks again 🙂
