### ISSUE TITLE
[BUG] nhentai invalid JSON for: xxxxx

### ISSUE THREAD

**Issue by erickyun** [gan-of-culture/get-sauce#82]
**Describe the bug**
I'm receiving this error 
`
get-sauce https://nhentai.net/g/364616/
2022/05/18 14:46:54 invalid JSON for: 364616
`
Can't download from nhentai?

**Expected behavior**
start downloading from nhentai

**Desktop (please complete the following information):**
 - OS: Android 11 Termux, Xiaomi Redmi Note 8 Pro

**Comment by gan-of-culture** [comment]
It works for me on Windows 11 64-bit. I am pretty sure this is sometimes related to them changing the cloudflare protection and sometimes challenge every request. Just try it again later :)

**Comment by erickyun** [comment]
yes you're right thanks. it did work later. I'm closing the issue.
