### ISSUE TITLE
[BUG] <download only 10 videos per page>

### ISSUE THREAD

**Issue by freddiehdxd** [gan-of-culture/get-sauce#89]
l try to download this page 
https://www.cartoonpornvideos.com/videos/straight/all-recent-2.html
but script only download the first 10 videos after it stop

**Comment by gan-of-culture** [comment]
Thanks for reporting! I found the issue and it is a easy fix. I'll update get-sauce as soon as most of the websites supported are working again so I don't have to disable too many tests.
