### ISSUE TITLE
[FEATURE]: hentaienvy and hentaizap

### ISSUE THREAD

**Issue by cc713** [gan-of-culture/get-sauce#97]
- **Website URL**: https://hentaienvy.com
- **Website URL**: https://hentaizap.com

**Comment by gan-of-culture** [comment]
Thanks for the recommendation! I will take a look at it later today :)

**Comment by gan-of-culture** [comment]
Luckily there is already a extractor for these kinds of sites so I only had to make small changes. Please test it and if you have any issues get back to me.
